draw_set_font(font_large_hud)
draw_text_color2(153, 8, "Guardians", c_white, c_silver, 1, c_black, c_black, 0.5)
draw_set_font(font_med_hud)
draw_sprite(spr_skullkey, 0, 209, 880)
draw_number(228, 874, store.have_skullkeys, c_white)
