
draw_set_font(font_upgrades)
draw_set_color(c_yellow)
draw_text(140,120,"Cards Received: "+string(cardsRecieved))
draw_set_color(c_white)
draw_text(140,150,"Inheritance x"+string(got_card_inheritance))
draw_text(140,180,"Heartpiece x"+string(got_card_heartpiece))
draw_text(140,210,"Mineshaft x"+string(got_card_mineshaft))
draw_text(140,240,"Magic Orb x"+string(got_card_orb))
draw_text(140,270,"Critical Gold x"+string(got_card_critgold))
draw_text(140,300,"Raging Fury x"+string(got_card_rage))
draw_text(140,330,"Supply Drop x"+string(got_card_supplydrop))
draw_text(140,360,"Flying Axes x"+string(got_card_axes))
draw_text(140,390,"Evil Creed x"+string(got_card_evilcreed))
draw_text(140,420,"Mastery x"+string(got_card_mastery))
