draw_set_font(font_large_hud)
draw_text_color(85,8,"Permanent Upgrades",c_white,c_white,c_silver,c_silver,1)
draw_sprite(spr_show_gem,0,207,928)
draw_set_font(font_med_hud)
draw_text_color(222,920,calc_number(store.gems),c_white,c_white,c_silver,c_silver,1)
