draw_set_font(font_large_hud)
draw_text_color(165,8,"Statistics",c_white,c_white,c_silver,c_silver,1)

draw_set_font(font_med_hud)
draw_text_color(118,140,"Best Stage: "+calc_number(store.best_stage),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,170,"Total Runs: "+calc_number(store.total_runs),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,200,"Enemies Slain: "+calc_number(store.enemies_slain),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,230,"Bosses Slain: "+calc_number(store.bosses_slain),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,260,"Gems Earned: "+calc_number(store.gems_earned),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,290,"Gold Earned: "+calc_number(store.gold_earned),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,320,"Total Upgrades: "+calc_number(store.total_upgrades),c_white,c_white,c_silver,c_silver,1)
draw_text_color(118,350,"Challenges Completed: "+calc_number(store.challenges_completed),c_white,c_white,c_silver,c_silver,1)
